New branch
sebastech/software-product-sprint pull request #1
Opened 2020-02-25 04:28 UTC by sebastech

first pull request - portfolio

2020-02-25 18:35 UTC, KaylaNguyen reviewed
Overall looks good! A few comments about style.
This PR is pretty big. Might be better to split into smaller PRs next time :)

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/background.html
> +    <!--<title>My Portfolio - Sebastian Lopez</title>-->
Is this code commented out? If so, please remove it completely. Same for other files.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/background.html
> +
Remove extra new line. Same for other files.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +var myVar, canvas, ctx, x, y, dx, dy, factor, color, colorStr;
Global vars are discouraged in js. Can you make sure among these vars, only the one you absolutely need to be global are declared here?

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +    myVar = setInterval(draw, 10);
You may want to use a more descriptive variable name for this.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +          //c pressed
Proper comment starts with a full sentence. E.g. // When users press "c" key.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +      }else if(event.keyCode === 83){
Add space after bracket.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +      }else if(event.keyCode === 83){
You may want to add a comment here too for the keycode == 83.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +    //ctx.moveTo(108, 0.0);
Remove all comments that don't provide informational values.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/script.js
>    const greetings =
If you don't use this function, you can remove it.

2020-02-25 18:35 UTC, KaylaNguyen commented on portfolio/src/main/webapp/style.css
> +canvas { background: #ffd300; }
What is this for?

2020-02-25 23:25 UTC, sebastech commented on portfolio/src/main/webapp/style.css
> +canvas { background: #ffd300; }
it makes the canvas background yellow

2020-02-26 00:33 UTC, KaylaNguyen reviewed
Looks good!

2020-02-26 00:33 UTC, KaylaNguyen commented on portfolio/src/main/webapp/background.html
> +</html>
Add new lines at end of html files. Same for other files.

2020-02-26 00:33 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +          //When users press "c" key.
nit: add space between // and comment.

2020-02-26 00:33 UTC, KaylaNguyen commented on portfolio/src/main/webapp/game.js
> +    console.log("in draw star");
Remove logging code.

2020-02-26 23:00 UTC, KaylaNguyen commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    response.getWriter().println("<h1>Hello Sebastian!</h1>");
Is this part of assignment 2? If so, can we make this part of a different PR?

2020-02-28 19:16 UTC, KaylaNguyen requested changes

2020-02-28 19:16 UTC, KaylaNguyen commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    response.getWriter().println("<h1>Hello Sebastian!</h1>");
Reopen this thread.
Can you remove this file out of this PR? Once you do, this PR will be purely for assignment 1 and good to submit :)

2020-03-01 06:30 UTC, KaylaNguyen reviewed
I think you want to "uncommit" instead of remove the file. If you commit this deleted file, the file in the master branch will also be deleted.
You can follow steps 1-3 in the 1st answer here https://stackoverflow.com/questions/18357511/git-remove-committed-file-after-push

2020-03-10 02:42 UTC, KaylaNguyen approved these changes

2020-03-23 03:45 UTC, merged